// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3VlJa06c_TWkMSrrJVUYZzCzrS9NUi2E',
    appId: '1:10591646344:web:e6245581824172d461e53d',
    messagingSenderId: '10591646344',
    projectId: 'bath-random',
    authDomain: 'bath-random.firebaseapp.com',
    storageBucket: 'bath-random.appspot.com',
    measurementId: 'G-RCK62W45EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChWN7SgGQCI_jW7AYhonkaYbvU8AwdPRY',
    appId: '1:10591646344:android:065f4ef17453ae8261e53d',
    messagingSenderId: '10591646344',
    projectId: 'bath-random',
    storageBucket: 'bath-random.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtlVg2TQEMB_XMRPWfwdMb3JekoAYXsZM',
    appId: '1:10591646344:ios:1d124519d821906061e53d',
    messagingSenderId: '10591646344',
    projectId: 'bath-random',
    storageBucket: 'bath-random.appspot.com',
    iosClientId: '10591646344-1ij51ohj7mlb3oe86j8c3lri2et40enu.apps.googleusercontent.com',
    iosBundleId: 'com.example.bathRandom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtlVg2TQEMB_XMRPWfwdMb3JekoAYXsZM',
    appId: '1:10591646344:ios:1d124519d821906061e53d',
    messagingSenderId: '10591646344',
    projectId: 'bath-random',
    storageBucket: 'bath-random.appspot.com',
    iosClientId: '10591646344-1ij51ohj7mlb3oe86j8c3lri2et40enu.apps.googleusercontent.com',
    iosBundleId: 'com.example.bathRandom',
  );
}
